INSERT INTO products 
(detail_desc, factory, image, name, price, short_desc, sold, target) VALUES
('Kệ sách tổ ong 8 ô đa năng là giải pháp nội thất thông minh không thể thiếu cho các căn hộ hiện đại, được sản xuất từ chất liệu gỗ MDF lõi xanh chống ẩm nhập khẩu Thái Lan cao cấp. Bề mặt sản phẩm phủ lớp Melamine dày dặn công nghệ mới, không chỉ mang lại khả năng chống trầy xước và thấm nước vượt trội mà còn giữ màu sắc vân gỗ luôn tươi mới, bền đẹp theo thời gian lên đến 10 năm. Điểm nhấn của sản phẩm nằm ở thiết kế module linh hoạt, cho phép gia chủ tùy ý đặt đứng làm giá sách tiết kiệm diện tích, hoặc xoay ngang biến tấu thành kệ Tivi, vách ngăn phân chia không gian thoáng đãng hay bục trưng bày đồ decor ấn tượng. Kết cấu các ô vuông đều tăm tắp được liên kết bằng hệ thống ốc cam chốt âm thẩm mỹ, đảm bảo khả năng chịu lực cực tốt, giúp bạn thoải mái lưu trữ sách báo nặng mà không lo cong vênh.',
'Hoàng Anh', 'image_product_1.jpg', 'Kệ tổ ong 8 ô', 179000, 'kệ tổ ong 8 ô, vân gỗ, hiện đại', 100, 'kệ'),

('Tủ quần áo 4 cánh mở sở hữu thiết kế thông minh kết hợp kệ trang trí bên hông tiện lợi, là sự lựa chọn hoàn hảo để nâng tầm không gian phòng ngủ sang trọng. Sản phẩm sử dụng cốt gỗ MDF lõi xanh chống ẩm dày 17mm cứng cáp, đã qua xử lý sấy khô nghiêm ngặt để triệt tiêu hoàn toàn tình trạng cong vênh hay mối mọt trong khí hậu nóng ẩm. Khoang chứa bên trong siêu rộng rãi được chia ngăn khoa học, bao gồm thanh treo inox 304 chịu lực để treo sơ mi, veston phẳng phiu và nhiều đợt kệ xếp đồ gấp gọn gàng. Cánh tủ sử dụng bản lề giảm chấn cao cấp giúp đóng mở êm ái, không gây tiếng ồn, mang lại trải nghiệm sử dụng tinh tế và bền bỉ theo năm tháng.',
'Hòa Phát', 'image_product_2.jpg', 'Tủ quần áo cánh mở nhiều ngăn', 9100000, 'Tủ quần áo cánh mở nhiều ngăn kết hợp thông minh gỗ MDF cao cấp sang trọng', 152, 'tủ'),

('Tủ nhựa Kata nổi bật với trọng lượng siêu nhẹ nhưng độ bền cơ học cực cao nhờ sử dụng nhựa PP nguyên sinh an toàn tuyệt đối cho sức khỏe, không lo ẩm mốc hay mối mọt bất chấp thời tiết nồm ẩm miền Bắc. Chân tủ được trang bị hệ thống 4 bánh xe chịu lực xoay 360 độ linh hoạt, giúp các bà nội trợ dễ dàng di chuyển tủ để vệ sinh gầm sàn mà không tốn sức. Thiết kế thông minh tích hợp 2 ngăn kéo nhỏ có khóa an toàn phía trên cùng, là nơi lý tưởng để bảo quản ví tiền, trang sức hay giấy tờ riêng tư. Họa tiết in 3D sắc nét, trang nhã, không bong tróc, phù hợp thẩm mỹ của cả sinh viên, người đi làm hay các gia đình trẻ năng động.',
'Hòa Phát', 'image_product_3.jpg', 'Tủ nhựa lớn Kata', 995000, 'tủ nhựa lớn kata với kiểu dáng trang nhã và họa tiết bắt mắt', 222, 'tủ'),

('Tủ vải khung thép mạ kẽm phiên bản nâng cấp là giải pháp lưu trữ quần áo tiết kiệm và hiệu quả nhất cho sinh viên và người thuê trọ. Khung tủ được làm từ thép ống đường kính lớn mạ kẽm sáng bóng, chịu lực tốt, không gỉ sét, đảm bảo kết cấu vững chãi không rung lắc. Áo tủ sử dụng vải không dệt 3 lớp dày dặn, dẻo dai, chống thấm nước và ngăn bụi bẩn, côn trùng xâm nhập cực tốt. Các khớp nối bằng nhựa ABS nguyên khối chịu va đập cao giúp việc tháo lắp trở nên đơn giản và nhanh chóng chỉ trong 15 phút mà không cần dụng cụ hỗ trợ, cực kỳ thuận tiện mỗi khi bạn cần chuyển chỗ ở.',
'Hòa Phát', 'image_product_4.jpg', 'Tủ quần áo vải inox', 229000, 'Tủ quần áo vải inox dễ lắp ráp ổn định và bền bỉ', 421, 'tủ'),

('Kệ để giày dép 5 tầng sử dụng khung inox 201 sáng bóng, chống ăn mòn, đảm bảo khả năng chịu lực mạnh mẽ lên đến 50kg mà không bị biến dạng hay rỉ sét theo thời gian. Sản phẩm được trang bị áo vải che bụi 3 mặt kín đáo và nắp đậy phía trước linh hoạt, giúp bảo vệ bộ sưu tập giày dép đắt tiền của bạn luôn sạch sẽ, tránh xa bụi bẩn và sự nhòm ngó của thú cưng. Thiết kế lắp ghép thông minh cho phép người dùng dễ dàng tháo bớt các tầng giữa để tạo khoảng trống lớn chứa bốt cao cổ hoặc giày cao gót, giúp tối ưu hóa không gian sảnh nhà một cách gọn gàng và ngăn nắp nhất.',
'Hòa Phát', 'image_product_5.jpg', 'Kệ để giày dép 5 tầng KHUNG INOX', 312000, 'kệ để giày dép 5 tầng KHUNG INOX, tủ giá đựng giày có nắp đậy chống bụi không gỉ có thể xếp chồng', 258, 'kệ'),

('Tuyệt phẩm kệ Tivi phong cách Indochine (Đông Dương) với kích thước bề thế 2m7 x 2m8, được ví như một tác phẩm nghệ thuật tạo điểm nhấn đẳng cấp cho phòng khách biệt thự. Chất liệu gỗ MDF chống ẩm đạt chuẩn E1 Châu Âu, bề mặt sơn men sứ PU 2K láng mịn qua 5 lớp xử lý kỹ càng, kết hợp cánh kính cường lực khung nhôm mạ vàng sang trọng. Hệ thống đèn LED dây hắt sáng cảm biến tự động bên trong tủ giúp tôn lên vẻ đẹp lung linh của các vật phẩm trưng bày như bình cổ, rượu quý. Sản phẩm có kết cấu vững chắc, độ bền lên tới 20 năm và chế độ bảo hành chính hãng dài hạn, khẳng định vị thế của gia chủ.',
'Hòa Phát', 'image_product_6.jpg', 'Kệ Tivi Cánh Kính', 28500000, 'Kệ Tivi Cánh Kính Phong Cách Đông Dương Indochine, Dài 2m7 x Sâu 40cm x Cao 2m8', 15, 'kệ'),

('Tủ rượu Homeline mang đến vẻ đẹp sang trọng, quý phái và tiện nghi vượt trội cho không gian phòng khách hoặc văn phòng giám đốc. Thiết kế đa năng thông minh kết hợp hài hòa giữa các ô tổ ong trưng bày rượu vang, ngăn kệ để sách, đồ decor và hệ tủ cánh kín bên dưới để cất giữ ly cốc, phụ kiện gọn gàng. Gỗ công nghiệp MDF lõi xanh được xử lý tẩm sấy kỹ càng chống mối mọt tuyệt đối, bề mặt phủ Melamine vân gỗ óc chó hoặc sồi láng mịn dễ vệ sinh. Từng đường nét góc cạnh được bo viền tỉ mỉ, khẳng định gu thẩm mỹ tinh tế và sành điệu của người sở hữu.',
'Hòa Phát', 'image_product_7.jpg', 'Tủ rượu phòng khách Homeline', 3600000, 'Tủ rượu phòng khách Homeline, tủ decor văn phòng, Kệ sách đa năng nhiều ngăn D80', 280, 'tủ'),

('Kệ Tivi trưng bày được chế tác hoàn toàn từ gỗ Sồi (Oak) tự nhiên nhập khẩu Bắc Mỹ kết hợp Veneer sồi cao cấp, mang lại vẻ đẹp ấm cúng, mộc mạc nhưng vô cùng sang trọng. Kích thước dài 2m rộng rãi, kết cấu khung xương chịu tải trọng lớn, phù hợp hoàn hảo với các dòng TV màn hình rộng từ 65 inch trở lên. Thiết kế chân gỗ tiện tròn cao thoáng gầm giúp robot hút bụi dễ dàng hoạt động vệ sinh sàn nhà. Vân gỗ tự nhiên sắc nét, màu sắc tươi sáng không xuống màu theo thời gian, càng dùng càng bóng đẹp, là điểm nhấn đắt giá cho không gian giải trí của gia đình.',
'Baya', 'image_product_8.jpg', 'Kệ Tivi trưng bày', 15800000, 'Kệ tủ Tivi - Kệ Trưng Bày/ Tủ Trang Trí Dài 2m x Sâu 45cm x Cao 86cm', 150, 'kệ'),

('Tủ gương Lavabo phong cách Hàn Quốc là giải pháp 2 trong 1 thông minh giúp tiết kiệm diện tích tối đa cho các phòng tắm nhỏ hẹp chung cư. Sản phẩm sử dụng chất liệu nhựa composite đặc nguyên khối siêu nhẹ, cam kết chống nước và oxi hóa tuyệt đối 100% ngay cả trong môi trường ẩm ướt thường xuyên. Phía sau mặt gương tráng bạc sắc nét là khoang chứa đồ rộng rãi, được chia tầng khoa học để bạn cất giữ bàn chải, kem đánh răng, mỹ phẩm, dao cạo râu gọn gàng. Bản lề inox chống gỉ giúp đóng mở nhẹ nhàng, giúp không gian nhà tắm của bạn luôn ngăn nắp, khô ráo và hiện đại.',
'Baya', 'image_product_9.jpg', 'Tủ gương Lavabo Hàn Quốc', 1036000, 'Tủ gương Lavabo Hàn Quốc Siêu Nhẹ Chống Oxi Hóa Phong Cách Hàn Quốc Kích Thước 75x65cm', 200, 'tủ'),

('Tủ trang điểm mini tai mèo dễ thương, tuy kích thước nhỏ gọn nhưng sở hữu sức chứa đáng nể, là trợ thủ đắc lực cho các cô nàng yêu làm đẹp. Thiết kế thông minh với nhiều ngăn, hộc phân chia khoa học chuyên biệt cho son môi, hộp phấn, cọ trang điểm và các chai lọ dưỡng da skincare. Chất liệu nhựa ABS cao cấp dày dặn, bề mặt trơn bóng dễ lau chùi, không bám bụi. Tích hợp gương soi sắc nét tiện lợi có thể điều chỉnh góc độ. Đây là món phụ kiện decor "must-have" giúp biến góc bàn làm việc hay bàn học thành bàn trang điểm chuyên nghiệp chỉ trong tích tắc.',
'Baya', 'image_product_10.jpg', 'Tủ Để Đồ Trang Điểm Mini', 290000, 'Tủ Để Đồ Trang Điểm Mini, Kệ Đựng Mỹ Phẩm Mini Có Gương Tai Mèo, Hộp Mỹ Phẩm Thiết Kế đa năng Tiện Lợi', 900, 'tủ'),

('Tủ quần áo phong cách Hàn Quốc ghi điểm tuyệt đối bởi thiết kế tối giản (Minimalism) nhưng vô cùng tinh tế, cực kỳ phù hợp cho các căn hộ chung cư mini hoặc homestay decor. Chiều cao 1m6 vừa vặn tầm với người Việt, tối ưu không gian sử dụng với thanh treo đồ dài chịu lực tốt và các ngăn kệ bên dưới để xếp quần áo gấp hoặc hộp giày. Gỗ MDF lõi xanh nhập khẩu được xử lý cạnh viền PVC kỹ càng chống cong vênh, bề mặt mịn màng mang lại cảm giác hiện đại. Màu trắng hoặc vân gỗ sồi trang nhã giúp không gian phòng ngủ trở nên rộng rãi, thoáng đãng và ấm cúng hơn bao giờ hết.',
'Baya', 'image_product_11.jpg', 'Tủ Quần Áo Người Lớn', 1900000, 'Tủ Quần Áo Người Lớn Cao 1m6 Gỗ MDF Thiết Kế Hiện Đại, Phù Hợp Với Không Gian Gia Đình', 98, 'tủ'),

('Tủ trưng bày Lego chuyên dụng cao cấp với chất liệu Mica Acrylic trong suốt như kính cường lực nhưng nhẹ và an toàn hơn, giúp bộ sưu tập mô hình đắt giá của bạn luôn sáng bóng và không bám bụi bẩn. Khung tủ làm từ tre ép tự nhiên đã qua xử lý chống mối mọt, kết cấu chắc chắn, kết hợp đế xoay 360 độ giúp người xem dễ dàng chiêm ngưỡng vẻ đẹp của mô hình từ mọi góc độ. Thiết kế lắp ghép mộng âm dương thông minh, cho phép bạn dễ dàng tháo rời để vệ sinh hoặc xếp chồng nhiều tủ lên nhau để mở rộng không gian trưng bày theo thời gian sưu tập.',
'Baya', 'image_product_12.jpg', 'Tủ trưng bày Lego acrylic', 5200000, 'Tủ trưng bày Lego acrylic trong suốt giả kính mỹ phẩm kệ khói tủ xoay khói giá khối xây tủ trưng bày', 999, 'tủ'),

('Kệ dán tường đa năng GADI là giải pháp decor không khoan đục tuyệt vời với miếng dán công nghệ Nano siêu dính chịu lực tốt lên đến 5kg, cam kết không làm bong tróc hay hỏng bề mặt tường. Thiết kế hình thú ngộ nghĩnh, màu sắc pastel dễ thương, phù hợp để đựng gia vị nhà bếp hoặc dùng làm kệ đựng bàn chải, mỹ phẩm, dầu gội trong nhà tắm. Chất liệu nhựa PP an toàn, bền bỉ, thiết kế đáy có lỗ thoát nước thông minh giúp đồ đạc luôn khô ráo, sạch sẽ, ngăn ngừa vi khuẩn tích tụ, giúp không gian sống thêm phần sinh động và gọn gàng.',
'Baya', 'image_product_13.jpg', 'Kệ Nhà Bếp Dán Tường GADI', 529000, 'Kệ Đựng Đồ Nhà Bếp Dán Tường GADI Chịu Lực Tốt, Giá Đựng Mỹ Phẩm, Đồ Đa Năng Hình Dễ Thương', 586, 'kệ'),

('Kệ sách xoay 360 độ thông minh là món quà tuyệt vời giúp bé yêu hào hứng hơn với việc đọc sách và rèn luyện thói quen ngăn nắp. Sản phẩm sử dụng hệ thống mâm xoay bi bạc đạn thép cao cấp vận hành cực kỳ êm ái, bền bỉ, xoay nhẹ nhàng ngay cả khi đầy sách. Các tầng kệ được thiết kế vách ngăn chống rơi sách thông minh, kích thước khoang cao phù hợp với cả sách khổ A4 và truyện tranh lớn. Chất liệu gỗ MDF an toàn, bề mặt láng mịn, toàn bộ các góc cạnh được bo tròn mềm mại đảm bảo an toàn tuyệt đối, tránh va đập gây thương tích cho trẻ nhỏ khi sử dụng.',
'Baya', 'image_product_14.jpg', 'Kệ Đựng Sách Xoay 360', 2550000, 'Kệ Đựng Sách Xoay 360 Độ Kệ Gỗ Trang Trí Sách Vở Xoay Cho Bé KTT-142 ZataFu', 120, 'kệ'),

('Giá gia vị điện thông minh EUROGOLD là bước đột phá công nghệ 4.0 cho căn bếp hiện đại, biến việc nấu nướng trở thành niềm vui. Cơ chế nâng hạ tự động mượt mà chỉ với một nút chạm cảm ứng, giúp việc lấy gia vị trên tủ bếp cao trở nên nhẹ nhàng, đặc biệt hữu ích cho người có chiều cao khiêm tốn. Chất liệu hợp kim nhôm cao cấp mạ Crom sáng bóng chống oxy hóa, chịu tải trọng lớn tới 15kg. Hệ thống cảm biến vật cản thông minh sẽ tự động dừng lại khi gặp chướng ngại vật, đảm bảo an toàn tuyệt đối cho người dùng và các thiết bị bếp khác.',
'Hoàng Anh', 'image_product_15.jpg', 'Giá Gia Vị Điện', 10000000, 'Giá Gia Vị Điện Tự Động Thông Minh, Kệ Gia Vị Điện Tự Động THƯƠNG HIỆU EUROGOLD', 48, 'giá'),

('Giá treo quần áo chữ A khung thép Cacbon siêu bền là sản phẩm "best-seller" nhờ khả năng chịu tải khủng, không lo gãy đổ hay cong vênh dù treo kín quần áo mùa đông nặng nề. Thiết kế thông minh tích hợp thêm 1 tầng kệ để giày dép, hộp đồ bên dưới giúp tối ưu hóa không gian lưu trữ cho phòng trọ sinh viên hoặc căn hộ diện tích nhỏ. Kiểu dáng tối giản (Minimalist), sơn tĩnh điện đen/trắng hiện đại, các chi tiết ốc vít chắc chắn, lắp ráp cực kỳ dễ dàng. Đây là lựa chọn lý tưởng phù hợp với lối sống năng động, xê dịch của các bạn trẻ hiện nay.',
'Hoàng Anh', 'image_product_16.jpg', 'Giá Treo Quần Áo', 1120000, 'Giá Treo Quần Áo Kệ Treo Quần Áo Kim Loại Đơn Giản Chắc Chắn Tiện Lợi Nhiều Giàn Phơi', 512, 'giá'),

('Nệm lò xo túi Firmrest Supreme ứng dụng công nghệ sản xuất nệm hàng đầu Châu Âu, mang lại trải nghiệm giấc ngủ đẳng cấp chuẩn khách sạn 5 sao ngay tại nhà. Hệ thống hàng nghìn lò xo túi độc lập cao cấp giúp nâng đỡ cột sống theo đường cong tự nhiên, triệt tiêu hoàn toàn dao động lan truyền, không gây tiếng động hay rung lắc khi người bên cạnh trở mình. Bề mặt nệm được phủ lớp vải kháng khuẩn và chống dị ứng độc quyền, bảo vệ sức khỏe hô hấp, mang lại cảm giác êm ái, thoáng mát và thư thái tuyệt đối, giúp bạn tái tạo năng lượng hiệu quả sau ngày dài.',
'Hoàng Anh', 'image_product_17.jpg', 'Đệm lò xo Túi Cao Cấp', 13336120, 'Đệm lò xo Túi Cao Cấp Dunlopillo Firmrest Extra Nâng Đỡ Cơ Thể Tối Ưu, Kháng Khuẩn và Dị Ứng', 19, 'đệm'),

('Tủ sấy quần áo thông minh là vị cứu tinh đắc lực cho mọi gia đình trong những ngày mưa phùn gió bấc hay nồm ẩm ướt át. Công nghệ sấy nhiệt đối lưu 360 độ hiện đại giúp làm khô quần áo nhanh chóng chỉ trong vài chục phút mà vẫn giữ nguyên hương thơm nước xả vải dễ chịu. Hai chế độ sấy nóng/lạnh linh hoạt cùng tính năng hẹn giờ tự động giúp bảo vệ sợi vải không bị khô cứng, co rút hay phai màu. Thiết kế tủ vuông với 2 tầng treo rộng rãi, khung inox chịu lực tốt, đáp ứng hoàn hảo nhu cầu sấy khô quần áo cho cả gia đình 4-5 người.',
'Hoàng Anh', 'image_product_18.jpg', 'Tủ sấy quần áo', 675000, 'Tủ sấy 2 tầng, máy sấy quần áo 2 chế độ nóng-lạnh, tiết kiệm điện, nhanh khô hữu ích', 697, 'tủ'),

('Kệ trưng bày nghệ thuật phong cách Trung Hoa mới (New Chinese Style) là điểm nhấn ấn tượng, mang lại vẻ đẹp Á Đông đương đại cho nhà hàng, quán trà đạo hoặc phòng khách gia đình. Sự kết hợp hài hòa giữa khung sắt sơn tĩnh điện đen mờ cứng cáp và các đợt gỗ MDF vân gỗ trầm tạo nên vẻ đẹp vừa cổ điển, hoài niệm vừa hiện đại, phóng khoáng. Thiết kế đa năng dạng mở (open shelf) giúp sản phẩm có thể dùng làm vách ngăn không gian, kệ trưng bày rượu quý, ấm trà hay giá sách, giúp phân chia các khu vực chức năng một cách tinh tế mà vẫn giữ được sự thông thoáng.',
'Hoàng Anh', 'image_product_19.jpg', 'Tủ trưng bày nghệ thuật', 2302000, 'Tủ trưng bày nghệ thuật sắt cho nhà hàng, kệ sách, giá rượu, tủ rượu, kệ lưu trữ, vách ngăn văn phòng, tủ phòng khách', 152, 'tủ'),

('Sofa giường thông minh 2 trong 1 (Sofa Bed) là giải pháp nội thất thần kỳ giúp giải quyết bài toán không gian cho nhà phố hay căn hộ nhỏ. Chỉ với thao tác kéo nhẹ nhàng chưa đầy 5 giây, chiếc ghế sofa sang trọng phòng khách sẽ lập tức biến hình thành chiếc giường ngủ êm ái rộng rãi cho 2 người nằm. Sản phẩm tích hợp ngăn chứa đồ bí mật rộng rãi bên dưới đệm ngồi, giúp bạn cất chăn, gối, drap giường gọn gàng. Vỏ bọc vải Nano công nghệ mới chống thấm nước, chống bám bẩn, tặng kèm 2 gối tựa lưng êm ái, mang lại sự tiện nghi và thẩm mỹ tối đa.',
'Hoàng Anh', 'image_product_20.jpg', 'Sofa giường thông minh', 12300000, 'Sofa giường thông minh có ngăn chứa đồ, giường sofa gấp gọn bọc vải nano cao cấp hàng nhập khẩu (Tặng kèm 2 gối)', 158, 'sofa'),

('Kệ 3 tầng Pihouse là giải pháp thông minh tận dụng triệt để không gian "chết" phía trên bồn cầu hoặc máy giặt, giúp phòng tắm nhỏ trở nên gọn gàng bất ngờ. Khung kệ được làm từ thép sơn tĩnh điện dày dặn kết hợp Inox 304 chống gỉ sét tuyệt đối trong môi trường ẩm ướt. Thiết kế 3 tầng kệ lưới thoáng khí rộng rãi, đủ chỗ để khăn tắm, giấy vệ sinh, hóa chất giặt tẩy ngăn nắp. Chân đế thông minh có thể điều chỉnh độ cao để cân bằng trên sàn nhà không bằng phẳng, lắp đặt dễ dàng bằng các khớp nối mà không cần khoan tường đục gạch phức tạp.',
'Baya', 'image_product_21.jpg', 'Kệ Bồn Cầu/Máy Giặt 3 Tầng Pihouse', 236000, 'Kệ 3 tầng thép sơn tĩnh điện, tận dụng không gian sau bồn cầu/máy giặt', 485, 'kệ'),

('Bàn trà chữ U di động thông minh (C-table) với thiết kế chân lệch độc đáo, cho phép phần chân bàn luồn sâu vào gầm ghế sofa hoặc gầm giường ngủ một cách gọn gàng. Mặt bàn làm từ gỗ MDF phủ melamine chống xước, chống thấm nước, kích thước nhỏ gọn nhưng đủ rộng để đặt laptop làm việc, ly cafe hay sách báo. Sản phẩm được trang bị hệ thống 4 bánh xe chịu lực xoay 360 độ linh hoạt có khóa hãm an toàn, giúp bạn dễ dàng di chuyển bàn đến mọi vị trí trong nhà để phục vụ nhu cầu làm việc, ăn nhẹ hay giải trí mọi lúc mọi nơi.',
'Hòa Phát', 'image_product_22.jpg', 'Bàn Trà Sofa Chữ U Di Động Có Bánh Xe', 149000, 'Bàn trà mini chữ U 2 tầng, có bánh xe, đa năng, mặt gỗ MDF khung sắt hiện đại', 205, 'bàn'),

('Giường ngủ An Nhiên mang phong cách tối giản (Minimalism) hiện đại, lược bỏ các chi tiết rườm rà để tập trung vào công năng và chất lượng, phù hợp với xu hướng nội thất mới. Chất liệu gỗ MDF lõi xanh chống ẩm nhập khẩu đã qua xử lý nghiêm ngặt trên dây chuyền công nghệ Đức, cam kết không cong vênh, co ngót trong 10 năm sử dụng. Kết cấu hệ khung giường dạng hộp vững chãi, các mối ghép chính xác tuyệt đối giúp giường không phát ra tiếng kêu cọt kẹt khó chịu khi cử động. Sản phẩm được thiết kế dạng module lắp ráp sẵn một phần, giúp bạn dễ dàng tự vận chuyển và hoàn thiện lắp đặt tại nhà.',
'Baya', 'image_product_23.jpg', 'Giường Ngủ Hiện Đại Gỗ MDF An Nhiên', 2190000, 'Giường ngủ hiện đại, gỗ MDF chống ẩm, đã lắp ráp sẵn, phong cách tối giản', 121, 'giường'),

('Giá treo quần áo kim loại đa tầng thiết kế thông minh giúp tối ưu hóa không gian lưu trữ lên đến 200% cho các tín đồ thời trang (Fashionista). Khung kim loại sơn tĩnh điện 2 lớp dày dặn, chịu lực cực tốt, kết hợp thanh treo dài để treo váy áo, veston và các tầng kệ lưới thép phía dưới để giày dép, túi xách, phụ kiện. Thiết kế dạng mở (Open Closet) giúp bạn dễ dàng quan sát, lựa chọn và phối đồ nhanh chóng mỗi sáng. Sản phẩm có tính thẩm mỹ cao, phù hợp cho phòng ngủ cá nhân, căn hộ studio hoặc làm giá kệ trưng bày cho các shop quần áo thời trang.',
'Hoàng Anh', 'image_product_24.jpg', 'Giá Treo Quần Áo Kim Loại Đa Tầng', 349000, 'Giá treo quần áo kim loại, đơn giản, chắc chắn, có kệ để đồ tiện lợi', 750, 'giá'),

('Sofa băng Musche House Decor là sự kết hợp hoàn hảo giữa thẩm mỹ tinh tế Châu Âu và công năng sử dụng vượt trội. Khung ghế làm từ gỗ sồi tự nhiên đã qua tẩm sấy chống mối mọt, chịu lực cực tốt, đảm bảo sự vững chãi. Hệ thống đệm mút Việt Nhật đàn hồi cao kết hợp lò xo túi độc lập giúp chống xẹp lún hiệu quả, mang lại cảm giác ngồi êm ái nhưng vẫn nâng đỡ tốt. Vỏ bọc vải nỉ nhung hoặc vải bố cao cấp thoáng mát, màu sắc đa dạng tùy chọn theo sở thích. Sản phẩm được cam kết bảo hành khung xương chính hãng lên đến 24 tháng, mang lại vẻ đẹp sang trọng đẳng cấp cho phòng khách.',
'Baya', 'image_product_25.jpg', 'Sofa Băng Musche House Decor Cao Cấp', 5990000, 'Sofa băng cao cấp, thiết kế hiện đại, cứng cáp, bảo hành 24 tháng', 85, 'sofa'),

('Bộ bàn đa năng TM COLIF 3in1 là siêu phẩm nội thất thông minh "biến hình" dành riêng cho các căn hộ chung cư hiện đại. Sở hữu hệ khung cơ khí nâng hạ trợ lực cao cấp nhập khẩu, sản phẩm dễ dàng biến đổi công năng từ một chiếc bàn trà thấp sang trọng thành bàn làm việc tiện lợi hoặc bàn ăn rộng rãi cho 6 người chỉ trong 3 giây. Hệ thống lò xo trợ lực giúp thao tác nâng hạ nhẹ nhàng, êm ái, an toàn cho cả phụ nữ và người già. Ngăn chứa đồ bí mật ẩn bên trong thân bàn giúp bạn cất giữ bộ ấm chén, laptop, sách báo, giúp không gian phòng khách luôn gọn gàng, ngăn nắp và đầy bất ngờ.',
'Hoàng Anh', 'image_product_26.jpg', 'Bộ Bàn Đa Năng TM COLIF Cao Cấp 3in1', 8990000, 'Bộ bàn ghế đa năng COLIF 3in1 (Bàn trà-Bàn ăn-Bàn làm việc), nội thất sang trọng', 17, 'bàn'),

('Kệ nhà tắm KIVA được chế tác từ nhôm hàng không (Space Grade Aluminum) cao cấp, vật liệu chuyên dùng trong ngành vũ trụ, cam kết không gỉ sét, không bong tróc sơn dù tiếp xúc trực tiếp với nước và hóa chất hàng ngày. Bề mặt sơn tĩnh điện màu đen mờ (Matte Black) sang trọng, chống bám vân tay, phù hợp với mọi phong cách nhà tắm hiện đại. Công nghệ lắp đặt đột phá sử dụng keo dán chuyên dụng siêu dính nhập khẩu Đức, chịu tải trọng tới 20kg mà không cần khoan đục làm hỏng gạch ốp tường, đồng thời cho phép tháo dời để vệ sinh dễ dàng bất cứ lúc nào.',
'Hòa Phát', 'image_product_27.jpg', 'Kệ Nhà Tắm KIVA Nhôm Hàng Không Dán Tường', 99000, 'Kệ nhà tắm nhôm hàng không cao cấp, dán tường không cần khoan, màu đen', 152, 'kệ'),

('Tủ nhựa ngăn kéo trong suốt đa năng là giải pháp lưu trữ khoa học giúp bạn dễ dàng quản lý đồ đạc mà không cần tốn thời gian lục tìm. Sản phẩm được làm từ nhựa PP nguyên sinh dẻo dai, không mùi, không chứa BPA độc hại, an toàn tuyệt đối cho sức khỏe. Thiết kế dạng module lắp ghép thông minh cho phép người dùng linh hoạt tháo rời hoặc xếp chồng thêm tầng tùy theo nhu cầu sử dụng thực tế. Các ngăn kéo được thiết kế kín khít tuyệt đối giúp chống bụi bẩn và côn trùng xâm nhập, lý tưởng để đựng thuốc y tế, văn phòng phẩm, đồ lót hoặc phụ kiện trang sức nhỏ.',
'Hòa Phát', 'image_product_28.jpg', 'Tủ Đựng Đồ Ngăn Kéo Trong Suốt Đa Năng', 185000, 'Tủ đựng đồ nhựa nhiều tầng, ngăn kéo trong suốt, tháo rời, chống bụi', 1250, 'tủ'),

('Nệm Hybrid Havas Fullmoon dày 27cm là tuyệt tác của sự êm ái, kết hợp hoàn hảo giữa hệ thống lò xo túi 3 vùng nâng đỡ cơ thể theo trọng điểm và lớp foam Silkfoam độc quyền êm ái tựa lông vũ. Cấu trúc hybrid hiện đại giúp tản nhiệt nhanh gấp 2 lần nệm thường, đảm bảo sự thoáng khí tối đa, không gây hầm nóng lưng ngay cả trong mùa hè nhiệt đới. Công nghệ cách ly chuyển động (Motion Isolation) tiên tiến giúp bạn ngủ ngon và sâu giấc dù người nằm cạnh có thường xuyên trở mình. Sản phẩm được hút chân không cuộn gọn gàng trong hộp và bảo hành chính hãng lên đến 10 năm.',
'Baya', 'image_product_29.jpg', 'Nệm Hybrid Havas Fullmoon 27cm Cao Cấp', 9500000, 'Nệm hybrid 27cm, lò xo túi 3 vùng và SILKFOAM™, thoáng khí, bảo hành 10 năm', 55, 'đệm'),

('Tủ lưu trữ phong cách Nhật Bản (Japandi Style) mang lại vẻ đẹp tinh tế, mộc mạc và sự gọn gàng đặc trưng của xứ sở hoa anh đào cho không gian sống. Sự kết hợp độc đáo giữa khung sắt sơn tĩnh điện thanh mảnh nhưng chắc chắn và các hộc gỗ MDF cửa lật tạo nên tổng thể hài hòa. Cánh tủ được thiết kế rãnh trượt thông minh để trưng bày bìa tạp chí, tranh ảnh nghệ thuật cực "chill". Sản phẩm đa năng phù hợp làm kệ sách thư viện, tủ trang trí phòng khách (Sideboard) hoặc tủ đựng đồ chơi giáo dục cho bé, giúp rèn luyện thói quen ngăn nắp từ nhỏ.',
'Hoàng Anh', 'image_product_30.jpg', 'Tủ Lưu Trữ Đa Năng Phong Cách Nhật Bản', 3350000, 'Tủ/Kệ đa năng cửa lật, phong cách Nhật Bản, kết hợp gỗ và sắt, trưng bày tạp chí', 155, 'tủ'),

('Bàn Gaming chữ K chân cong thiết kế công thái học (Ergonomic) với mặt bàn khuyết nhẹ phía trước giúp ôm sát người ngồi, tối ưu tư thế cho game thủ chiến game hàng giờ liền không mỏi. Hệ khung chân sắt hộp chữ K sơn tĩnh điện dày dặn cực ngầu và chắc chắn, đảm bảo không rung lắc khi vẩy chuột cường độ cao, chịu tải trọng lớn lên đến 100kg. Mặt bàn gỗ MDF phủ Carbon Fiber chống trầy xước, tích hợp 2 lỗ đi dây điện gọn gàng. Tặng kèm kệ lửng tiện lợi để đặt màn hình, loa hoặc case máy tính, giúp góc máy Battle Station của bạn trở nên chuyên nghiệp và đẳng cấp hơn.',
'Hoàng Anh', 'image_product_31.jpg', 'Bàn Làm Việc Gaming Chữ K Cong Kèm Kệ', 699000, 'Bàn gaming chữ K cong, chân sắt sơn tĩnh điện, kèm kệ lửng, chắc chắn', 620, 'bàn'),

('Tủ quần áo dạng kệ treo mở (Open Wardrobe Concept) là xu hướng nội thất hiện đại đang "làm mưa làm gió" tại các nước phương Tây. Thiết kế thông minh kết hợp hài hòa giữa khung gỗ MDF vân gỗ ấm áp và thanh treo kim loại sơn tĩnh điện đen mạnh mẽ. Cấu trúc tủ bao gồm các ngăn kéo kín ray bi 3 tầng để cất đồ riêng tư (đồ lót, phụ kiện) và các đợt kệ mở thoáng đãng để túi xách, giày dép hoặc vali du lịch. Giải pháp này giúp căn phòng trở nên rộng rãi, thoáng đãng hơn nhiều so với việc sử dụng tủ cánh kín truyền thống cục mịch, đồng thời giúp quần áo luôn khô thoáng, tránh ẩm mốc.',
'Baya', 'image_product_32.jpg', 'Tủ/Kệ Treo Quần Áo Gỗ Có Ngăn Kín', 1150000, 'Tủ gỗ dạng kệ treo quần áo, có ngăn chứa đồ/ngăn kéo kín, hàng nhập khẩu, tiện lợi', 280, 'tủ'),

('Bộ bàn ăn gấp gọn thông minh là "cứu cánh" hoàn hảo cho những căn bếp nhỏ hẹp diện tích khiêm tốn. Khi gấp gọn 2 cánh, bàn chỉ chiếm diện tích như một chiếc kệ trang trí nhỏ bề ngang 30cm, giải phóng hoàn toàn không gian đi lại. Khi mở rộng tối đa, bàn cung cấp chỗ ngồi thoải mái cho 4-6 người ăn. Khung thép hộp dày 1.2mm chịu lực tốt, sơn tĩnh điện chống gỉ sét. Mặt bàn gỗ công nghiệp dày 17mm phủ lớp giả đá Marble sang trọng, chống trầy xước, chịu nhiệt tốt và dễ dàng vệ sinh dầu mỡ. Chân bàn tích hợp bánh xe di chuyển tiện lợi 360 độ, có chốt khóa bánh chắc chắn an toàn khi sử dụng.',
'Hoà Phát', 'image_product_33.jpg', 'Bộ Bàn Ăn Gấp Gọn Thông Minh Khung Thép', 4990000, 'Bộ bàn ăn gấp gọn thông minh, khung thép sơn tĩnh điện, mặt gỗ giả đá, đã lắp ráp', 95, 'bàn'),

('Bàn sofa Green House GR801 mang đậm hơi thở phong cách Bắc Âu (Scandinavian) với vẻ đẹp thanh lịch, nhẹ nhàng và tinh tế. Mặt bàn làm từ gỗ MDF lõi xanh chống ẩm phủ Melamine cao cấp, giúp chống thấm nước tuyệt đối, dễ dàng lau sạch vết ố trà cafe chỉ với một đường lau nhẹ. Chân bàn được thiết kế dáng sải nhẹ thanh thoát nhưng vô cùng vững chãi nhờ kết cấu mộng gỗ hoặc vít sắt chắc chắn. Kích thước nhỏ gọn, trọng lượng nhẹ, dễ dàng di chuyển và kết hợp hoàn hảo với sofa văng, sofa góc L, tạo nên góc tiếp khách ấm cúng và đầy tính nghệ thuật.',
'Hoàng Anh', 'image_product_34.jpg', 'Bàn Sofa Phòng Khách Phong Cách Bắc Âu GR801', 590000, 'Bàn trà sofa, phong cách Bắc Âu, mặt gỗ MDF, chân sắt/gỗ chắc chắn, decor phòng khách', 580, 'bàn'),

('Kệ sách gỗ đứng B11 gây ấn tượng thị giác mạnh mẽ nhờ thiết kế các ngăn kệ lệch tầng độc đáo, phá vỡ sự đơn điệu của các mẫu kệ truyền thống. Bên cạnh các ngăn kệ mở rộng rãi để trưng bày sách và đồ decor (chậu cây, khung ảnh), sản phẩm còn tinh tế tích hợp thêm 2 ngăn kéo kín phía dưới cùng ray trượt êm ái, giúp bạn cất giữ giấy tờ quan trọng, sạc cáp, văn phòng phẩm tránh bụi bẩn. Chất liệu gỗ MDF lõi xanh cao cấp dày 17mm đảm bảo độ bền đẹp, khả năng chịu lực tốt, màu sắc vân gỗ tự nhiên sang trọng phù hợp với mọi không gian nội thất từ phòng khách đến phòng làm việc.',
'Baya', 'image_product_35.jpg', 'Kệ Sách Gỗ Đứng Có Ngăn Kéo Phong Cách Bắc Âu', 1999000, 'Kệ sách gỗ MDF nhiều tầng, có ngăn kéo, chống mối mọt, phong cách Bắc Âu', 310, 'kệ'),

('Ghế Gaming công thái học (Ergonomic Gaming Chair) bọc da PU cao cấp với bề mặt da mềm mịn, lỗ thoáng khí li ti giúp mang lại cảm giác ngồi êm ái, mát mẻ dù sử dụng liên tục trong 8-10 tiếng. Thiết kế tựa lưng uốn cong S-shape ôm sát cột sống, đi kèm gối tựa đầu và gối đệm thắt lưng giúp định hình tư thế ngồi chuẩn, giảm thiểu tối đa tình trạng đau mỏi vai gáy và thoát vị đĩa đệm. Khung chân thép đúc nguyên khối chịu tải trọng khủng lên đến 150kg, Piston thủy lực Class 4 bền bỉ, cùng khả năng ngả lưng 135 độ giúp bạn có thể tranh thủ chợp mắt nghỉ trưa thoải mái ngay tại bàn làm việc.',
'Hoàng Anh', 'image_product_36.jpg', 'Ghế Gaming Công Thái Học Da PU', 1899000, 'ghế gaming, da PU, khung kim loại, văn phòng', 150, 'ghế'),

('Ghế gấp văn phòng đệm da là sự lựa chọn kinh tế và hoàn hảo cho các không gian làm việc linh hoạt, phòng họp hoặc trung tâm đào tạo. Khung ghế làm từ thép ống sơn tĩnh điện dày dặn, các khớp nối được gia cố chắc chắn đảm bảo an toàn tuyệt đối, không lỏng lẻo sau thời gian dài sử dụng. Mặt ngồi và tựa lưng được bọc nệm mút dày dặn, phủ lớp da PVC êm ái, dễ dàng lau chùi vệ sinh vết bẩn. Điểm cộng lớn nhất là khả năng gấp gọn siêu nhanh, có thể xếp chồng hoặc dựng vào góc tường khi không sử dụng, giúp giải phóng và tiết kiệm diện tích tối đa cho văn phòng.',
'Baya', 'image_product_37.jpg', 'Ghế gấp văn phòng đệm da', 259000, 'ghế gấp gọn, khung thép, bọc da, decor', 680, 'ghế'),

('Ghế đôn sofa tròn màu xám ghi trung tính thanh lịch, là mảnh ghép hoàn hảo dễ dàng phối hợp (mix & match) với mọi bộ sofa và phong cách nội thất. Khung xương bên trong làm từ gỗ tự nhiên đã qua xử lý mối mọt chắc chắn, chịu lực tốt cho cả người lớn đứng lên. Đệm mút D40 dày dặn chống xẹp lún, bọc vải nỉ cao cấp nhập khẩu mang lại cảm giác ngồi êm ái, mềm mại. Sản phẩm cực kỳ đa năng: dùng làm ghế phụ khi nhà có đông khách, ghế ngồi trang điểm xinh xắn cho chị em hoặc dùng để gác chân thư giãn khi nằm xem tivi trên sofa lớn.',
'Hòa Phát', 'image_product_38.jpg', 'Ghế đôn sofa màu xám', 519000, 'ghế đôn, màu xám, mút dày, bàn trang điểm', 420, 'ghế'),

('Ghế Eames chân gỗ đan chéo (Eames DSW Chair) là biểu tượng bất hủ của thiết kế nội thất hiện đại thế kỷ 20, chưa bao giờ lỗi mốt. Thân ghế đúc từ nhựa PP nguyên sinh dẻo dai với độ cong hõm lưng hoàn hảo giúp nâng đỡ cột sống, mang lại cảm giác thoải mái tối đa. Chân ghế làm từ gỗ sồi tự nhiên màu vàng sáng ấm áp, kết hợp hệ giằng khung thép sơn tĩnh điện đen đan chéo tạo kết cấu tháp Eiffel vững chãi. Tính ứng dụng cực cao: phù hợp làm ghế ăn gia đình, ghế quán cafe, trà sữa, ghế làm việc tại nhà hay ghế tiếp khách văn phòng sáng tạo.',
'Hòa Phát', 'image_product_39.jpg', 'Ghế Eames Chân Gỗ Đan', 185000, 'ghế eames, chân gỗ, cafe, văn phòng', 999, 'ghế'),

('Ghế lười hạt đậu (Bean Bag) là "thiên đường thư giãn" mang đến trải nghiệm êm ái tuyệt đối sau ngày dài làm việc mệt mỏi. Bên trong ghế chứa hàng ngàn hạt xốp EPS nguyên sinh kích thước 2-3mm chuyển động linh hoạt theo từng cử động của cơ thể, giúp massage nhẹ nhàng vùng lưng và vai gáy. Vỏ ghế được may từ vải thô bố hoặc nhung lạnh cao cấp, thoáng mát, thấm hút mồ hôi tốt, an toàn cho da. Thiết kế khóa kéo đôi (double-zip) chắc chắn giúp ngăn hạt xốp rơi ra ngoài, đồng thời giúp bạn dễ dàng tháo vỏ để giặt vệ sinh định kỳ. Món đồ yêu thích của cả người lớn để đọc sách và trẻ em để vui chơi.',
'Hoàng Anh', 'image_product_40.jpg', 'Ghế lười hạt đậu thư giãn', 1159000, 'ghế lười, hạt đậu, decor, thư giãn', 345, 'ghế');